### ISSUE TITLE
Ubuntu PySDD Installation Failure

### ISSUE THREAD

**Issue by zeirew** [wannesm/PySDD#28]
Trying to install PySDD on Ubuntu 20.04 using Python 3.8 continually fails for me when running `pip install pysdd`.

I've installed libpython3-dev & python3-dev. Additionally, I've tried to use other recommended commands from previous issue threads, such as `pip install -vvv --upgrade --force-reinstall --no-deps pysdd`. However, the installation fails every time. 

Below, I've provided the output when running `pip install pysdd`. In this case, the error seems to stem from the use of the -march=native flag. 

```
 × Running setup.py install for pysdd did not run successfully.
  │ exit code: 1
  ╰─> [156 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-ppc64le-3.8
      creating build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/util.py -> build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/__main__.py -> build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/iterator.py -> build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/__init__.py -> build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/cli.py -> build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/wmcstochastic.py -> build/lib.linux-ppc64le-3.8/pysdd
      running egg_info
      writing PySDD.egg-info/PKG-INFO
      writing dependency_links to PySDD.egg-info/dependency_links.txt
      writing entry points to PySDD.egg-info/entry_points.txt
      writing requirements to PySDD.egg-info/requires.txt
      writing top-level names to PySDD.egg-info/top_level.txt
      reading manifest file 'PySDD.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'PySDD.egg-info/SOURCES.txt'
      copying pysdd/compiler_c.pxd -> build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/fnf_c.pxd -> build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/io_c.pxd -> build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/sdd.c -> build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/sdd.pyx -> build/lib.linux-ppc64le-3.8/pysdd
      copying pysdd/sddapi_c.pxd -> build/lib.linux-ppc64le-3.8/pysdd
      creating build/lib.linux-ppc64le-3.8/pysdd/lib
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0
      copying pysdd/lib/libsdd-2.0/sddapi.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/build
      copying pysdd/lib/libsdd-2.0/build/libsdd.a -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/build
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/debug
      copying pysdd/lib/libsdd-2.0/debug/libsdd.a -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/debug
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/include
      copying pysdd/lib/libsdd-2.0/include/iterators.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/include
      copying pysdd/lib/libsdd-2.0/include/macros.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/include
      copying pysdd/lib/libsdd-2.0/include/parameters.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/include
      copying pysdd/lib/libsdd-2.0/include/sdd.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/include
      copying pysdd/lib/libsdd-2.0/include/stacks.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/include
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src
      copying pysdd/lib/libsdd-2.0/src/util.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src
      copying pysdd/lib/libsdd-2.0/src/verify.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src
      copying pysdd/lib/libsdd-2.0/src/version.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/computed.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/count_and_size.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/gc.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/hash.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/memory.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/multiply.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/nodes.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/partitions.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/references.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/replace.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/shadows.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      copying pysdd/lib/libsdd-2.0/src/basic/sort.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/basic
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/fnf
      copying pysdd/lib/libsdd-2.0/src/fnf/io.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/fnf
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/manager
      copying pysdd/lib/libsdd-2.0/src/manager/copy.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/manager
      copying pysdd/lib/libsdd-2.0/src/manager/interface.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/manager
      copying pysdd/lib/libsdd-2.0/src/manager/manager.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/manager
      copying pysdd/lib/libsdd-2.0/src/manager/stats.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/manager
      copying pysdd/lib/libsdd-2.0/src/manager/variables.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/manager
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/apply.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/bits.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/cardinality.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/condition.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/copy.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/count.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/essential_vars.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/exists.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/exists_multiple.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/exists_multiple_static.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/forall.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/io.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/model_count.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/rename_vars.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/size.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      copying pysdd/lib/libsdd-2.0/src/sdds/wmc.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/sdds
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_fragments
      copying pysdd/lib/libsdd-2.0/src/vtree_fragments/construction.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_fragments
      copying pysdd/lib/libsdd-2.0/src/vtree_fragments/moves.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_fragments
      copying pysdd/lib/libsdd-2.0/src/vtree_fragments/operations.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_fragments
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_operations
      copying pysdd/lib/libsdd-2.0/src/vtree_operations/cartesian_product.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_operations
      copying pysdd/lib/libsdd-2.0/src/vtree_operations/dissect.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_operations
      copying pysdd/lib/libsdd-2.0/src/vtree_operations/limits.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_operations
      copying pysdd/lib/libsdd-2.0/src/vtree_operations/op_left_rotate.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_operations
      copying pysdd/lib/libsdd-2.0/src/vtree_operations/op_right_rotate.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_operations
      copying pysdd/lib/libsdd-2.0/src/vtree_operations/op_swap.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_operations
      copying pysdd/lib/libsdd-2.0/src/vtree_operations/rollback.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_operations
      copying pysdd/lib/libsdd-2.0/src/vtree_operations/split.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_operations
      copying pysdd/lib/libsdd-2.0/src/vtree_operations/vtree_ops.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_operations
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_search
      copying pysdd/lib/libsdd-2.0/src/vtree_search/auto.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_search
      copying pysdd/lib/libsdd-2.0/src/vtree_search/search.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_search
      copying pysdd/lib/libsdd-2.0/src/vtree_search/state.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtree_search
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtrees
      copying pysdd/lib/libsdd-2.0/src/vtrees/compare.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtrees
      copying pysdd/lib/libsdd-2.0/src/vtrees/edit.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtrees
      copying pysdd/lib/libsdd-2.0/src/vtrees/io.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtrees
      copying pysdd/lib/libsdd-2.0/src/vtrees/maps.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtrees
      copying pysdd/lib/libsdd-2.0/src/vtrees/moves.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtrees
      copying pysdd/lib/libsdd-2.0/src/vtrees/static.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtrees
      copying pysdd/lib/libsdd-2.0/src/vtrees/vtree.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/libsdd-2.0/src/vtrees
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/examples
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/examples/src
      copying pysdd/lib/sdd-2.0/examples/src/circuit-gc.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/examples/src
      copying pysdd/lib/sdd-2.0/examples/src/circuit.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/examples/src
      copying pysdd/lib/sdd-2.0/examples/src/test-1.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/examples/src
      copying pysdd/lib/sdd-2.0/examples/src/test-2.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/examples/src
      copying pysdd/lib/sdd-2.0/examples/src/test-3.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/examples/src
      copying pysdd/lib/sdd-2.0/examples/src/test-4.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/examples/src
      copying pysdd/lib/sdd-2.0/examples/src/test-5.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/examples/src
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/include
      copying pysdd/lib/sdd-2.0/include/compiler.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/include
      copying pysdd/lib/sdd-2.0/include/fnf.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/include
      copying pysdd/lib/sdd-2.0/include/io.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/include
      copying pysdd/lib/sdd-2.0/include/sddapi.h -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/include
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/lib
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/lib/Darwin
      copying pysdd/lib/sdd-2.0/lib/Darwin/libsdd.a -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/lib/Darwin
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/lib/Darwin/debug
      copying pysdd/lib/sdd-2.0/lib/Darwin/debug/libsdd.a -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/lib/Darwin/debug
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/lib/Linux
      copying pysdd/lib/sdd-2.0/lib/Linux/libsdd.a -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/lib/Linux
      copying pysdd/lib/sdd-2.0/lib/Linux/libsdd.so -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/lib/Linux
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/lib/Windows
      copying pysdd/lib/sdd-2.0/lib/Windows/libsdd.a -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/lib/Windows
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/src
      copying pysdd/lib/sdd-2.0/src/getopt.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/src
      copying pysdd/lib/sdd-2.0/src/main.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/src
      creating build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/src/fnf
      copying pysdd/lib/sdd-2.0/src/fnf/compiler.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/src/fnf
      copying pysdd/lib/sdd-2.0/src/fnf/fnf.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/src/fnf
      copying pysdd/lib/sdd-2.0/src/fnf/io.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/src/fnf
      copying pysdd/lib/sdd-2.0/src/fnf/utils.c -> build/lib.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/src/fnf
      running build_ext
      Compiler type: unix
      Compiler name: powerpc64le-linux-gnu-gcc
      --debug: 0
      --usecysignals: 0
      building 'pysdd.sdd' extension
      creating build/temp.linux-ppc64le-3.8
      creating build/temp.linux-ppc64le-3.8/pysdd
      creating build/temp.linux-ppc64le-3.8/pysdd/lib
      creating build/temp.linux-ppc64le-3.8/pysdd/lib/sdd-2.0
      creating build/temp.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/src
      creating build/temp.linux-ppc64le-3.8/pysdd/lib/sdd-2.0/src/fnf
      powerpc64le-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fexceptions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -fexceptions -Ipysdd/lib/sdd-2.0/include -Ipysdd/src -Ipysdd/lib/sdd-2.0/src -Ipysdd/lib/sdd-2.0/src/fnf -fPIC -I/home/username/.local/lib/python3.8/site-packages/cysignals -I/usr/include/python3.8 -c pysdd/sdd.c -o build/temp.linux-ppc64le-3.8/pysdd/sdd.o -O3 -march=native -std=c99
      powerpc64le-linux-gnu-gcc: error: unrecognized command line option ‘-march=native’; did you mean ‘-mcpu=native’?
      error: command 'powerpc64le-linux-gnu-gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
```

**Comment by wannesm** [comment]
This has been fixed in the main branch but not yet pushed to pypi. You can install directly from Github using `pip install git+https://github.com/wannesm/PySDD.git`

**Comment by zeirew** [comment]
@wannesm This still still fails for me when installing directly from Github. Here's the output: 

```
:~$pip install git+https://github.com/wannesm/PySDD.git

Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/wannesm/PySDD.git
  Cloning https://github.com/wannesm/PySDD.git to /tmp/pip-req-build-vov6m839
  Running command git clone --filter=blob:none --quiet https://github.com/wannesm/PySDD.git /tmp/pip-req-build-vov6m839
  Resolved https://github.com/wannesm/PySDD.git to commit 514a8da4c4e8ae1e6a53e64257faf28a30201a5b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cython>=0.29.6 in ./.local/lib/python3.8/site-packages (from PySDD==0.2.10) (0.29.32)
Building wheels for collected packages: PySDD
  Building wheel for PySDD (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for PySDD (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [226 lines of output]
      cysignals not found
      No module named 'cysignals'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-ppc64le-cpython-38
      creating build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/util.py -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/__main__.py -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/iterator.py -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/__init__.py -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/cli.py -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/wmcstochastic.py -> build/lib.linux-ppc64le-cpython-38/pysdd
      running egg_info
      creating PySDD.egg-info
      writing PySDD.egg-info/PKG-INFO
      writing dependency_links to PySDD.egg-info/dependency_links.txt
      writing entry points to PySDD.egg-info/entry_points.txt
      writing requirements to PySDD.egg-info/requires.txt
      writing top-level names to PySDD.egg-info/top_level.txt
      writing manifest file 'PySDD.egg-info/SOURCES.txt'
      reading manifest file 'PySDD.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'PySDD.egg-info/SOURCES.txt'
      copying pysdd/compiler_c.pxd -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/fnf_c.pxd -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/io_c.pxd -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/sdd.c -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/sdd.pyx -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/sddapi_c.pxd -> build/lib.linux-ppc64le-cpython-38/pysdd
      copying pysdd/weight_optimization_c.pxd -> build/lib.linux-ppc64le-cpython-38/pysdd
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/include
      copying pysdd/lib/sdd-2.0/include/compiler.h -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/include
      copying pysdd/lib/sdd-2.0/include/fnf.h -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/include
      copying pysdd/lib/sdd-2.0/include/io.h -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/include
      copying pysdd/lib/sdd-2.0/include/sddapi.h -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/include
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/lib
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/lib/Darwin
      copying pysdd/lib/sdd-2.0/lib/Darwin/libsdd.a -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/lib/Darwin
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/lib/Darwin-arm
      copying pysdd/lib/sdd-2.0/lib/Darwin-arm/libsdd.a -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/lib/Darwin-arm
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/lib/Linux
      copying pysdd/lib/sdd-2.0/lib/Linux/libsdd.a -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/lib/Linux
      copying pysdd/lib/sdd-2.0/lib/Linux/libsdd.so -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/lib/Linux
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/lib/Windows
      copying pysdd/lib/sdd-2.0/lib/Windows/libsdd.a -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/lib/Windows
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src
      copying pysdd/lib/sdd-2.0/src/getopt.c -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src
      copying pysdd/lib/sdd-2.0/src/main.c -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf
      copying pysdd/lib/sdd-2.0/src/fnf/compiler.c -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf
      copying pysdd/lib/sdd-2.0/src/fnf/fnf.c -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf
      copying pysdd/lib/sdd-2.0/src/fnf/io.c -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf
      copying pysdd/lib/sdd-2.0/src/fnf/utils.c -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd_extra
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd_extra/include
      copying pysdd/lib/sdd_extra/include/sddapi_extra.h -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/sdd_extra/include
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/include
      copying pysdd/lib/weight_optimization/include/arithmetic_ansi.h -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/include
      copying pysdd/lib/weight_optimization/include/lbfgs.h -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/include
      copying pysdd/lib/weight_optimization/include/weight_optimizer.h -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/include
      creating build/lib.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/src
      copying pysdd/lib/weight_optimization/src/lbfgs.c -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/src
      copying pysdd/lib/weight_optimization/src/weight_optimizer.c -> build/lib.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/src
      running build_ext
      Compiler type: unix
      Compiler name: powerpc64le-linux-gnu-gcc
      --debug: 0
      --usecysignals: 0
      building 'pysdd.sdd' extension
      creating build/temp.linux-ppc64le-cpython-38
      creating build/temp.linux-ppc64le-cpython-38/pysdd
      creating build/temp.linux-ppc64le-cpython-38/pysdd/lib
      creating build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0
      creating build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src
      creating build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf
      creating build/temp.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization
      creating build/temp.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/src
      powerpc64le-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fexceptions -g -fwrapv -O2 -Ipysdd/lib/sdd-2.0/include -Ipysdd/lib/weight_optimization/include -Ipysdd/lib/sdd_extra/include -Ipysdd/src -Ipysdd/lib/weight_optimization/src -Ipysdd/lib/sdd-2.0/src/fnf -Ipysdd/lib/sdd-2.0/src -fPIC -I/usr/include/python3.8 -c pysdd/lib/sdd-2.0/src/fnf/compiler.c -o build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf/compiler.o -O3 -std=c99
      pysdd/lib/sdd-2.0/src/fnf/compiler.c: In function ‘degenerate_fnf_test’:
      pysdd/lib/sdd-2.0/src/fnf/compiler.c:28:17: warning: comparison of integer expressions of different signedness: ‘int’ and ‘SddSize’ {aka ‘long unsigned int’} [-Wsign-compare]
         28 |   for(int i=0; i<count; i++) {
            |                 ^
      pysdd/lib/sdd-2.0/src/fnf/compiler.c: In function ‘fnf_to_sdd_auto’:
      pysdd/lib/sdd-2.0/src/fnf/compiler.c:46:17: warning: comparison of integer expressions of different signedness: ‘int’ and ‘SddSize’ {aka ‘long unsigned int’} [-Wsign-compare]
         46 |   for(int i=0; i<count; i++) {
            |                 ^
      pysdd/lib/sdd-2.0/src/fnf/compiler.c: In function ‘fnf_to_sdd_manual’:
      pysdd/lib/sdd-2.0/src/fnf/compiler.c:70:17: warning: comparison of integer expressions of different signedness: ‘int’ and ‘SddSize’ {aka ‘long unsigned int’} [-Wsign-compare]
         70 |   for(int i=0; i<count; i++) {
            |                 ^
      powerpc64le-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fexceptions -g -fwrapv -O2 -Ipysdd/lib/sdd-2.0/include -Ipysdd/lib/weight_optimization/include -Ipysdd/lib/sdd_extra/include -Ipysdd/src -Ipysdd/lib/weight_optimization/src -Ipysdd/lib/sdd-2.0/src/fnf -Ipysdd/lib/sdd-2.0/src -fPIC -I/usr/include/python3.8 -c pysdd/lib/sdd-2.0/src/fnf/fnf.c -o build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf/fnf.o -O3 -std=c99
      powerpc64le-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fexceptions -g -fwrapv -O2 -Ipysdd/lib/sdd-2.0/include -Ipysdd/lib/weight_optimization/include -Ipysdd/lib/sdd_extra/include -Ipysdd/src -Ipysdd/lib/weight_optimization/src -Ipysdd/lib/sdd-2.0/src/fnf -Ipysdd/lib/sdd-2.0/src -fPIC -I/usr/include/python3.8 -c pysdd/lib/sdd-2.0/src/fnf/io.c -o build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf/io.o -O3 -std=c99
      powerpc64le-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fexceptions -g -fwrapv -O2 -Ipysdd/lib/sdd-2.0/include -Ipysdd/lib/weight_optimization/include -Ipysdd/lib/sdd_extra/include -Ipysdd/src -Ipysdd/lib/weight_optimization/src -Ipysdd/lib/sdd-2.0/src/fnf -Ipysdd/lib/sdd-2.0/src -fPIC -I/usr/include/python3.8 -c pysdd/lib/sdd-2.0/src/fnf/utils.c -o build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf/utils.o -O3 -std=c99
      pysdd/lib/sdd-2.0/src/fnf/utils.c: In function ‘sort_litsets_by_lca’:
      pysdd/lib/sdd-2.0/src/fnf/utils.c:60:24: warning: comparison of integer expressions of different signedness: ‘SddLiteral’ {aka ‘long int’} and ‘SddSize’ {aka ‘long unsigned int’} [-Wsign-compare]
         60 |   for(SddLiteral i=0; i<size; i++) {
            |                        ^
      powerpc64le-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fexceptions -g -fwrapv -O2 -Ipysdd/lib/sdd-2.0/include -Ipysdd/lib/weight_optimization/include -Ipysdd/lib/sdd_extra/include -Ipysdd/src -Ipysdd/lib/weight_optimization/src -Ipysdd/lib/sdd-2.0/src/fnf -Ipysdd/lib/sdd-2.0/src -fPIC -I/usr/include/python3.8 -c pysdd/lib/weight_optimization/src/lbfgs.c -o build/temp.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/src/lbfgs.o -O3 -std=c99
      powerpc64le-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fexceptions -g -fwrapv -O2 -Ipysdd/lib/sdd-2.0/include -Ipysdd/lib/weight_optimization/include -Ipysdd/lib/sdd_extra/include -Ipysdd/src -Ipysdd/lib/weight_optimization/src -Ipysdd/lib/sdd-2.0/src/fnf -Ipysdd/lib/sdd-2.0/src -fPIC -I/usr/include/python3.8 -c pysdd/lib/weight_optimization/src/weight_optimizer.c -o build/temp.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/src/weight_optimizer.o -O3 -std=c99
      powerpc64le-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fexceptions -g -fwrapv -O2 -Ipysdd/lib/sdd-2.0/include -Ipysdd/lib/weight_optimization/include -Ipysdd/lib/sdd_extra/include -Ipysdd/src -Ipysdd/lib/weight_optimization/src -Ipysdd/lib/sdd-2.0/src/fnf -Ipysdd/lib/sdd-2.0/src -fPIC -I/usr/include/python3.8 -c pysdd/sdd.c -o build/temp.linux-ppc64le-cpython-38/pysdd/sdd.o -O3 -std=c99
      pysdd/sdd.c: In function ‘__pyx_pf_5pysdd_3sdd_7SddNode_73print_ptr’:
      pysdd/sdd.c:9797:46: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
       9797 |   __pyx_t_3 = __Pyx_PyInt_From_unsigned_int(((unsigned int)(&__pyx_v_self->_sddnode))); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 327, __pyx_L1_error)
            |                                              ^
      powerpc64le-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Lpysdd/lib/sdd-2.0/lib -Ipysdd/lib/sdd-2.0/include -Ipysdd/lib/weight_optimization/include -Ipysdd/lib/sdd_extra/include -Ipysdd/src -Ipysdd/lib/weight_optimization/src -Ipysdd/lib/sdd-2.0/src/fnf -Ipysdd/lib/sdd-2.0/src build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf/compiler.o build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf/fnf.o build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf/io.o build/temp.linux-ppc64le-cpython-38/pysdd/lib/sdd-2.0/src/fnf/utils.o build/temp.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/src/lbfgs.o build/temp.linux-ppc64le-cpython-38/pysdd/lib/weight_optimization/src/weight_optimizer.o build/temp.linux-ppc64le-cpython-38/pysdd/sdd.o pysdd/lib/sdd-2.0/lib/Linux/libsdd.a -L/usr/lib -o build/lib.linux-ppc64le-cpython-38/pysdd/sdd.cpython-38-powerpc64le-linux-gnu.so
      /usr/bin/ld: pysdd/lib/sdd-2.0/lib/Linux/libsdd.a(copy.o): Relocations in generic ELF (EM: 62)
      /usr/bin/ld: pysdd/lib/sdd-2.0/lib/Linux/libsdd.a(copy.o): Relocations in generic ELF (EM: 62)
      /usr/bin/ld: pysdd/lib/sdd-2.0/lib/Linux/libsdd.a: error adding symbols: file in wrong format
      collect2: error: ld returned 1 exit status
      /tmp/pip-build-env-lq482hzm/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /tmp/pip-build-env-lq482hzm/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'pysdd.lib' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'pysdd.lib' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'pysdd.lib' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'pysdd.lib' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/pip-build-env-lq482hzm/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'pysdd.lib.sdd_extra.include' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'pysdd.lib.sdd_extra.include' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'pysdd.lib.sdd_extra.include' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'pysdd.lib.sdd_extra.include' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/pip-build-env-lq482hzm/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'pysdd.lib.weight_optimization.include' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'pysdd.lib.weight_optimization.include' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'pysdd.lib.weight_optimization.include' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'pysdd.lib.weight_optimization.include' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/pip-build-env-lq482hzm/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'pysdd.lib.weight_optimization.src' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'pysdd.lib.weight_optimization.src' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'pysdd.lib.weight_optimization.src' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'pysdd.lib.weight_optimization.src' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      ********************************************
      ERROR: The C extension could not be compiled
      ********************************************
      error: command '/usr/bin/powerpc64le-linux-gnu-gcc' failed with exit code 1
      error: command '/usr/bin/powerpc64le-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PySDD
Failed to build PySDD
ERROR: Could not build wheels for PySDD, which is required to install pyproject.toml-based projects
```

**Comment by wannesm** [comment]
It appears from your log that you are using a powerpc based CPU. Can that be? The SDD library that this package wraps is not compiled for that architecture. I'm afraid you need to download the original library from http://reasoning.cs.ucla.edu/sdd/ and compile it on your platform. Afterwards you can put the resulting library in `pysdd/lib/sdd-2.0/lib/Linux/` (after downloading the repository) and reinstall from `python <path/to/pysdd/repo>/setup.py install`.

**Comment by zeirew** [comment]
@wannesm Thanks so much! This works great for me. I am working on a modern IBM POWER system.
